services:
  grafana:
    build:
      context: ./images/grafana
    volumes:
      - "grafana:/var/lib/grafana"
    restart: always
    networks:
      default:
      public:
  loki:
    build: ./images/loki
    volumes:
      - "loki:/loki"
    command: ["-config.file=/etc/loki/config.yaml"]
    restart: always
    networks:
      default:
      public:
  prometheus:
    build: ./images/prometheus
    volumes:
      - "prometheus:/prometheus"
    restart: always
    networks:
      default:
      public:
  alloy:
    build: images/alloy
    volumes:
      - "/var/log/journal/:/var/log/journal/"
      - "/run/log/journal/:/run/log/journal/"
      - "/etc/machine-id:/etc/machine-id"
      - "alloy:/var/lib/alloy/data"
    command: ["run", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
    restart: always
    depends_on:
      - loki
    networks:
      default:
      public:
  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    restart: always
    networks:
      default:
      public:
  reth:
    build:
      context: images/reth
    volumes:
      - "reth:/home/somebody/.local/share/reth"
      - "authrpc_secret:/home/somebody/authrpc-secret"
    restart: always
    networks:
      default:
      vpn_egress:
        priority: 1000
  lighthouse:
    build: images/lighthouse
    volumes:
      - "lighthouse:/home/somebody/.lighthouse"
      - "authrpc_secret:/home/somebody/authrpc-secret"
      - "./validator-pubkeys.txt:/home/somebody/validator-pubkeys.txt"
    environment:
      ETH1_HOST: reth
      BUILDER_URL: "http://mev-boost:18550"
    restart: always
    networks:
      default:
      vpn_egress:
        priority: 1000
  mev-boost:
    build:
      context: images/mev-boost
    restart: always
    networks:
      default:
      vpn_egress:
        priority: 1000
  ssh:
    build: images/ssh
    expose:
      - "5064"
      - "8081"
    ports:
      - "2222:22"
    volumes:
      - "supervisor_backups:/home/somebody/supervisor-backups"
      - "ssh_host_keys:/etc/ssh/host-keys"
      - "./authorized_keys:/home/somebody/.ssh/authorized_keys"
    restart: always
    networks:
      default:
        aliases:
          - validator-proxy
      public:
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    driver: bridge
    internal: true
  public:
    driver: bridge
  vpn_egress:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
volumes:
  grafana:
  loki:
  alloy:
  reth:
  prometheus:
  lighthouse:
  authrpc_secret:
  ssh_host_keys:
  supervisor_backups:
