services:
  grafana:
    build:
      context: ./images/grafana
    volumes:
      - "grafana:/var/lib/grafana"
    restart: always
  loki:
    build: ./images/loki
    volumes:
      - "loki:/loki"
    command: ["-config.file=/etc/loki/config.yaml"]
    restart: always
  prometheus:
    build: ./images/prometheus
    volumes:
      - "prometheus:/prometheus"
    restart: always
  alloy:
    build: images/alloy
    volumes:
      - "/var/log/journal/:/var/log/journal/"
      - "/run/log/journal/:/run/log/journal/"
      - "/etc/machine-id:/etc/machine-id"
      - "alloy:/var/lib/alloy/data"
    command: ["run", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
    restart: always
    depends_on:
      - loki
  reth:
    build:
      context: images/reth
    volumes:
      - "reth:/home/somebody/.local/share/reth"
      - "authrpc_secret:/home/somebody/authrpc-secret"
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    restart: always
  lighthouse:
    build: images/lighthouse
    volumes:
      - "lighthouse:/home/somebody/.lighthouse"
      - "authrpc_secret:/home/somebody/authrpc-secret"
      - "./validator-pubkeys.txt:/home/somebody/validator-pubkeys.txt"
    environment:
      ETH1_HOST: reth
      BUILDER_URL: "http://mev-boost:18550"
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
    restart: always
  mev-boost:
    build:
      context: images/mev-boost
    restart: always
  ssh:
    build: images/ssh
    expose:
      - "5064"
      - "8081"
    ports:
      - "2222:22"
    volumes:
      - "supervisor_backups:/home/somebody/supervisor-backups"
      - "ssh_host_keys:/etc/ssh/host-keys"
      - "./authorized_keys:/home/somebody/.ssh/authorized_keys"
    restart: always
    networks:
      default:
        aliases:
          - validator-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  default:
    driver: bridge
volumes:
  grafana:
  loki:
  alloy:
  reth:
  prometheus:
  lighthouse:
  authrpc_secret:
  ssh_host_keys:
  supervisor_backups:
